### ISSUE TITLE
TypeScript Error: key does not exist on type Range

### ISSUE THREAD

**Issue by mateja176** [hypeserver/react-date-range#439]
## Subject of the issue
Describe your issue here.

This is a type error, meaning that it does not impact the module's runtime. The prop `key` is missing in interface `Range`.
 
## [BUG] Bug Reproduce Steps
Tell us how to reproduce this issue.

The above assumption is backed by the following evidence:

```ts
export interface CommonCalendarProps {
  onChange?: (range: OnChangeProps) => void;
  // ...
}

export type OnChangeProps = Range | { selection: Range } | Date;

export interface Range {
    /** default: today */
    startDate?: Date;
    /** default: today */
    endDate?: Date;
}

```

Whereas at runtime:

```ts
<DateRangePicker
  onChange={(item) => {
    if ('selection' in item) {
        setRange(item.selection); // { startDate: 'foo', endDate: 'bar', key: 'selection' }
    }
  }}
  // ...
/>
```

## [BUG] Expected behaviour

The `Range` interface should be expanded to include the `key`. Like so:

```ts
export interface Range {
    /** default: today */
    startDate?: Date;
    /** default: today */
    endDate?: Date;
  key?: 'selection';
}
```
Perhaps a better alternative is to adjust the OnChangeProps type to:

```ts
export type OnChangeProps = Range | { selection: Range & { key: 'selection' } } | Date;
```

## Environment
Package Version: 1.1.3
React version: 16.9
Node version: 14
Browser: Chrome

**Comment by mwq27** [comment]
I think this was fixed:
```ts
export interface RangeWithKey extends Range {
    key: 'selection';
}

export type OnChangeProps = Range | { selection: RangeWithKey } | Date;
```

**Comment by naufaldi** [comment]
> I think this was fixed:
> 
> ```ts
> export interface RangeWithKey extends Range {
>     key: 'selection';
> }
> 
> export type OnChangeProps = Range | { selection: RangeWithKey } | Date;
> ```

still get error when use this type. say 
`Property 'selection' does not exist on type 'OnChangeProps'.
  Property 'selection' does not exist on type 'Date'.`

**Comment by rslohith** [comment]
Facing the same issue. @naufaldi were you able to get around this?

**Comment by rslohith** [comment]
Need to use `RangeKeyDict`
